/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_Migracion;

/**
 *
 * @author admin2
 */
public class FRM_Migracion extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Migracion
     */
    
    Controlador_FRM_Migracion controlador;
    
    public FRM_Migracion() {
        initComponents();
        
        
        controlador= new Controlador_FRM_Migracion(this);
         this.txt_Area_Reportes.setEditable(false);
        agregarEventoBotones(controlador);
       
        
        this.txt_Cedula.setEditable(true);
        
    }//fin cons
    
    public void agregarEventoBotones(Controlador_FRM_Migracion controlador)
    {
        this.btn_Atender.addActionListener(controlador);
        this.btn_Cantidad.addActionListener(controlador);
        this.btn_InfoClentes.addActionListener(controlador);
        this.btn_Modificar.addActionListener(controlador);
        this.btn_OrdenarMayorAMenor.addActionListener(controlador);
        this.btn_OrdenarMenorAMayor.addActionListener(controlador);
        this.btn_Promedio.addActionListener(controlador);
        this.btn_Registrar.addActionListener(controlador);
    }//fin agregar eventos
    
    
    public void inicio()
    {
        this.txt_Edad.setEditable(false);
        this.txt_Nombre.setEditable(false);
        this.comboBox_Priori.setEditable(false);
        
    }
    
    public void deshabilitarCedula()
    {
        
        this.txt_Cedula.setEnabled(false);
    }
    public void editar()
    {
        this.txt_Edad.setEditable(true);
        this.txt_Nombre.setEditable(true);
        this.comboBox_Priori.setEditable(true);
        
    }
    
    public String retornarCedula()
    {
        return this.txt_Cedula.getText();
    }
    
    public String[] retornarInformacion(){
        String[] informacion=new String [4];
        
        informacion[0]=this.txt_Cedula.getText();
        informacion[1]=this.txt_Nombre.getText();
        informacion[2]=this.txt_Edad.getText();
        informacion[3]=this.comboBox_Priori.getSelectedItem().toString();
        
       return informacion;
       
    }//fin retornar info
    
        public String[] devolverInfo(){
        String[] informacion=new String [3];
        
        informacion[0]=this.txt_Nombre.getText();
        informacion[1]=this.txt_Edad.getText();
        informacion[2]=this.comboBox_Priori.getSelectedItem().toString();
        
       return informacion;
       
    }//fin retornar info
    public void resetGUI()
    {
        this.txt_Cedula.setText("");
        this.txt_Edad.setText("");
        this.txt_Nombre.setText("");
        
    }
    
    public void asiganarTexto(String texto)
    {
        this.txt_Area_Reportes.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Cedula = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jl_Edad = new javax.swing.JLabel();
        jl_Priori = new javax.swing.JLabel();
        comboBox_Priori = new javax.swing.JComboBox();
        txt_Cedula = new javax.swing.JTextField();
        txt_Nombre = new javax.swing.JTextField();
        txt_Edad = new javax.swing.JTextField();
        btn_Registrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_Atender = new javax.swing.JButton();
        btn_Modificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Area_Reportes = new javax.swing.JTextArea();
        btn_OrdenarMenorAMayor = new javax.swing.JButton();
        btn_OrdenarMayorAMenor = new javax.swing.JButton();
        jl_Reportes = new javax.swing.JLabel();
        btn_InfoClentes = new javax.swing.JButton();
        btn_Promedio = new javax.swing.JButton();
        btn_Cantidad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_Cedula.setText("Cedula: ");

        jl_Nombre.setText("Nombre Completo: ");

        jl_Edad.setText("Edad: ");

        jl_Priori.setText("Prioridad del usuario:");

        comboBox_Priori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escoja un opcion", "7600", "Normal" }));

        btn_Registrar.setText("Registrar");

        jButton2.setText("Cancelar Cita");
        jButton2.setActionCommand("Cancelar");

        btn_Atender.setText("Atender Cliente");
        btn_Atender.setActionCommand("Atender");

        btn_Modificar.setText("Modificar");

        txt_Area_Reportes.setColumns(20);
        txt_Area_Reportes.setRows(5);
        jScrollPane1.setViewportView(txt_Area_Reportes);

        btn_OrdenarMenorAMayor.setText("<");

        btn_OrdenarMayorAMenor.setText(">");

        jl_Reportes.setText("Reportes: ");

        btn_InfoClentes.setText("Información de todos los clientes");
        btn_InfoClentes.setActionCommand("Informacion");

        btn_Promedio.setText("Promedio edad");
        btn_Promedio.setActionCommand("Promedio");

        btn_Cantidad.setText("Cantidad de  usuarios");
        btn_Cantidad.setActionCommand("Cantidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jl_Cedula)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jl_Nombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_Nombre))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jl_Edad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_Edad)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Registrar)
                                    .addComponent(btn_Modificar)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jl_Priori)
                                .addGap(18, 18, 18)
                                .addComponent(comboBox_Priori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(btn_OrdenarMenorAMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btn_OrdenarMayorAMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Reportes)
                            .addComponent(btn_Cantidad)
                            .addComponent(btn_InfoClentes)
                            .addComponent(btn_Promedio)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButton2)
                        .addGap(38, 38, 38)
                        .addComponent(btn_Atender)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Cedula)
                    .addComponent(txt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Registrar)
                    .addComponent(jl_Reportes))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Nombre)
                            .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Edad)
                            .addComponent(txt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Modificar))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btn_InfoClentes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Promedio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Priori)
                    .addComponent(comboBox_Priori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Cantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_OrdenarMenorAMayor)
                    .addComponent(btn_OrdenarMayorAMenor))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btn_Atender))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Migracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Migracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Migracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Migracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Migracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Atender;
    private javax.swing.JButton btn_Cantidad;
    private javax.swing.JButton btn_InfoClentes;
    private javax.swing.JButton btn_Modificar;
    private javax.swing.JButton btn_OrdenarMayorAMenor;
    private javax.swing.JButton btn_OrdenarMenorAMayor;
    private javax.swing.JButton btn_Promedio;
    private javax.swing.JButton btn_Registrar;
    private javax.swing.JComboBox comboBox_Priori;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jl_Cedula;
    private javax.swing.JLabel jl_Edad;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_Priori;
    private javax.swing.JLabel jl_Reportes;
    private javax.swing.JTextArea txt_Area_Reportes;
    private javax.swing.JTextField txt_Cedula;
    private javax.swing.JTextField txt_Edad;
    private javax.swing.JTextField txt_Nombre;
    // End of variables declaration//GEN-END:variables
}
